<?php
/**
 * Funcion de nuestro hook_menu()
 */

function webservicesphp_menu() {

	$items['webservicesphp/imagen'] = array(
	'title' => 'Imagenes',
		'page callback' => 'webservicesphp_printimage',
		'access callback' => TRUE,
	);

	$items['webservicesphp/recientes'] = array(
	'title' => 'Posts Recientes',
		'page callback' => 'webservicesphp_recent',
		'access callback' => TRUE,
	);

	return $items;
}

function webservicesphp_printimage() {
	$nid = 1;
	$node = node_load($nid);
	print drupal_render(node_view(node_load($nid)));
}

function webservicesphp_recent() {
	$today = getdate(); //Obtener fecha actual
	//Calcula la fecha siete dias antes
	$start_time = mktime(0, 0, 0, $today['mon'],($today['mday']-7), $today['year']);
	//Obtener todos los posts desde 7 dias antes hasta hoy
	$end_time = time();

	$query = db_select('node', 'n')
		->fields('n', array('nid','title','created'))
		->condition('status', 1) //publicados
		->condition('created', array($start_time, $end_time), 'BETWEEN')
		->orderBy('created', 'DESC') //Mas reciente primero
		->execute();
	//$stuff = $query->fetchAll();
	return $query;
}
